name: Publish to Docker Hub
on:
  workflow_dispatch: {}
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          docker buildx create --name builder --use --bootstrap
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag khulnasoft/tracker-tester:latest .
